# Generated by Django 5.2.16 on 2026-07-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
