# Generated by Django 5.2.16 on 2026-07-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobpost_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='work_arrangement',
            field=models.CharField(default=13.972222222222221, max_length=200),
            preserve_default=False,
        ),
    ]
