# Generated by Django 5.2.16 on 2026-07-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobpost_work_arrangement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='work_arrangement',
            new_name='job_type',
        ),
    ]
