# Generated by Django 5.2.16 on 2026-07-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
